name: Python, Poetry, Flake8, and Code Coverage

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Poetry
      run: |
        pip install poetry
        poetry install
      working-directory: ${{ github.workspace }}/refactorNCI

    - name: Run Flake8
      run: poetry run flake8 || true
      working-directory: ${{ github.workspace }}/refactorNCI
      
    - name: Install pytest
      run: poetry add --dev pytest pytest-cov
      working-directory: ${{ github.workspace }}/refactorNCI
      
    - name: Run Tests and Generate Code Coverage
      run: |
        poetry run pytest --cov=pyproject.toml
      working-directory: ${{ github.workspace }}/refactorNCI

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: ${{ github.workspace }}  # Adjust the path to your coverage report folder
