name: Python, Poetry, Flake8, and Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install Poetry
      run: |
        pip install poetry
        poetry install
      working-directory: ${{ github.workspace }}

    - name: Run Flake8
      run: poetry run flake8
      working-directory: ${{ github.workspace }}

    - name: Run Tests and Generate Code Coverage
      run: |
        poetry run pytest --cov=my_module --cov-fail-under=80  # Change 'my_module' to your actual module
      working-directory: ${{ github.workspace }}

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ${{ github.workspace }}/htmlcov  # Change the path to the directory containing your coverage report
